name: sample-workflow

on:
  push:
    branches:
      - main   # runs on every commit pushed to main

jobs:
  hello-world-job:
    runs-on: arc-runner-set
    steps:
      - name: Hello World Step
        run: echo "Hello, World!"
